manifest-version = 1

[products.ferrocene]
release = "beta-25.02-2025-01-25"
packages = [
    "rustc-${rustc-host}",
    "rust-std-${rustc-host}",
    "cargo-${rustc-host}",
    "llvm-tools-${rustc-host}",
    "rust-src",
    "rust-std-armv8r-none-eabihf",
    "rust-std-armv7r-none-eabihf",
]
